// ============================================================
// FIREBASE CONFIGURATION
// ============================================================
// WEEK 3: Replace the placeholder values below with YOUR
// Firebase project config from:
//   Firebase Console > Project Settings > Your Apps > Web App
//
// DO NOT edit this file until Week 3 (Deliverable 3).
// ============================================================

// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";

// 🛠️ THE FIX: This line imports the Firestore function
import { getFirestore } from "firebase/firestore";

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyCV7D-Ft8RKT4NJkNRp-eynHbL30qR0vZw",
  authDomain: "hawa-khana-restaurant.firebaseapp.com",
  projectId: "hawa-khana-restaurant",
  storageBucket: "hawa-khana-restaurant.firebasestorage.app",
  messagingSenderId: "491637108192",
  appId: "1:491637108192:web:5f8497affa111652e78f85",
  measurementId: "G-DYVMTDNWHE"
};

// Initialize Firebase
const app = initializeApp(firebaseConfig);

// Initialize Analytics (Optional, but good to have since you imported it)
const analytics = getAnalytics(app);

// Initialize Firestore and export it
export const db = getFirestore(app);
